(define (problem thief-5)
    (:domain thief)
    (:objects A B C D E F H J - location)
    (:init
        (Belief! (at-agent A) 2)
        (Belief! (not (at-agent B)) 2)
        (Belief! (not (at-agent C)) 2)
        (Belief! (not (at-agent D)) 2)
        (Belief! (not (at-agent E)) 2)
        (Belief! (not (at-agent F)) 2)
        (Belief! (not (at-agent H)) 2)
        (Belief! (not (at-agent J)) 2)

        (Belief! (at-trap A) -2)
        (Belief! (at-trap B) -1)
        (Belief! (at-trap C)  0) ; Don't need to explicitely declare
        (Belief! (at-trap D)  1)
        (Belief! (at-trap E)  1)
        (Belief! (at-trap F)  1)
        (Belief! (at-trap H)  0) ; Don't need to explicitely declare
        (Belief! (at-trap J) -2)

        (Belief! (CONNECTED A B) 2)
        (Belief! (CONNECTED A C) 2)
        (Belief! (CONNECTED A D) 2)
        (Belief! (not (CONNECTED A A)) 2)
        (Belief! (not (CONNECTED A E)) 2)
        (Belief! (not (CONNECTED A F)) 2)
        (Belief! (not (CONNECTED A H)) 2)
        (Belief! (not (CONNECTED A J)) 2)

        (Belief! (CONNECTED B E) 2)
        (Belief! (not (CONNECTED B A)) 2)
        (Belief! (not (CONNECTED B B)) 2)
        (Belief! (not (CONNECTED B C)) 2)
        (Belief! (not (CONNECTED B D)) 2)
        (Belief! (not (CONNECTED B F)) 2)
        (Belief! (not (CONNECTED B H)) 2)
        (Belief! (not (CONNECTED B J)) 2)

        (Belief! (CONNECTED E J) 2)
        (Belief! (not (CONNECTED E A)) 2)
        (Belief! (not (CONNECTED E B)) 2)
        (Belief! (not (CONNECTED E C)) 2)
        (Belief! (not (CONNECTED E D)) 2)
        (Belief! (not (CONNECTED E E)) 2)
        (Belief! (not (CONNECTED E F)) 2)
        (Belief! (not (CONNECTED E H)) 2)

        (Belief! (CONNECTED C F) 2)
        (Belief! (not (CONNECTED C A)) 2)
        (Belief! (not (CONNECTED C B)) 2)
        (Belief! (not (CONNECTED C C)) 2)
        (Belief! (not (CONNECTED C D)) 2)
        (Belief! (not (CONNECTED C E)) 2)
        (Belief! (not (CONNECTED C H)) 2)
        (Belief! (not (CONNECTED C J)) 2)

        (Belief! (CONNECTED F J) 2)
        (Belief! (not (CONNECTED F A)) 2)
        (Belief! (not (CONNECTED F B)) 2)
        (Belief! (not (CONNECTED F C)) 2)
        (Belief! (not (CONNECTED F D)) 2)
        (Belief! (not (CONNECTED F E)) 2)
        (Belief! (not (CONNECTED F F)) 2)
        (Belief! (not (CONNECTED F H)) 2)

        (Belief! (CONNECTED D H) 2)
        (Belief! (not (CONNECTED D A)) 2)
        (Belief! (not (CONNECTED D B)) 2)
        (Belief! (not (CONNECTED D C)) 2)
        (Belief! (not (CONNECTED D D)) 2)
        (Belief! (not (CONNECTED D E)) 2)
        (Belief! (not (CONNECTED D F)) 2)
        (Belief! (not (CONNECTED D J)) 2)

        (Belief! (CONNECTED H J) 2)
        (Belief! (not (CONNECTED H A)) 2)
        (Belief! (not (CONNECTED H B)) 2)
        (Belief! (not (CONNECTED H C)) 2)
        (Belief! (not (CONNECTED H D)) 2)
        (Belief! (not (CONNECTED H E)) 2)
        (Belief! (not (CONNECTED H F)) 2)
        (Belief! (not (CONNECTED H H)) 2)

        (Belief! (not caught) 2)
    )

    :goal (and
        (at-agent J)
        (not (caught))
    )
)